#!/usr/bin/env bash
# fix-audio-scheduling.sh — Fix real-time scheduling for SoundSync audio
#
# This script fixes the #1 cause of audio stuttering: all audio processes
# running at SCHED_OTHER (normal priority) instead of SCHED_FIFO/SCHED_RR.
#
# What it does:
#   1. Creates /etc/security/limits.d/99-soundsync-rt.conf (RT limits)
#   2. Installs rtkit-daemon if missing
#   3. Sets CPU governor to 'performance' (optional but recommended)
#   4. Restarts PipeWire and SoundSync to apply changes
#
# Usage: sudo bash scripts/fix-audio-scheduling.sh
#
# After running, verify with:
#   chrt -p $(pgrep -x pipewire)   # Should show SCHED_FIFO or SCHED_RR
#   chrt -p $(pgrep -x parec)      # Should show SCHED_OTHER (parec is a consumer)

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1"; }

if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (sudo bash $0)"
    exit 1
fi

# Detect the SoundSync user
if id -u soundsync &>/dev/null; then
    AUDIO_USER="soundsync"
elif [ -n "${SUDO_USER:-}" ]; then
    AUDIO_USER="$SUDO_USER"
else
    err "Cannot determine audio user. Specify with: AUDIO_USER=username sudo bash $0"
    exit 1
fi

AUDIO_UID=$(id -u "$AUDIO_USER")
echo "Configuring real-time audio scheduling for user: $AUDIO_USER (uid=$AUDIO_UID)"
echo ""

# ── Step 1: Create RT limits ───────────────────────────────────────────
LIMITS_FILE="/etc/security/limits.d/99-soundsync-rt.conf"
echo "--- Step 1: Configure RT scheduling limits ---"

cat > "$LIMITS_FILE" << EOF
# Real-time scheduling limits for SoundSync audio
# Generated by fix-audio-scheduling.sh on $(date '+%Y-%m-%d')
#
# rtprio 95  = allow SCHED_FIFO/SCHED_RR up to priority 95
# memlock     = prevent audio buffers from being swapped (causes latency)
# nice -15   = allow higher-than-normal scheduling priority

$AUDIO_USER  -  rtprio   95
$AUDIO_USER  -  memlock  unlimited
$AUDIO_USER  -  nice     -15

# Also apply to the audio group (for PipeWire running as this user)
@audio   -  rtprio   95
@audio   -  memlock  unlimited
@audio   -  nice     -15
EOF

log "Created $LIMITS_FILE"
cat "$LIMITS_FILE"
echo ""

# ── Step 2: Ensure rtkit is installed ──────────────────────────────────
echo "--- Step 2: Ensure rtkit-daemon is running ---"

if command -v rtkit-daemon &>/dev/null || dpkg -l rtkit 2>/dev/null | grep -q "^ii"; then
    log "rtkit package is installed"
else
    warn "rtkit not installed — installing..."
    apt-get install -y rtkit 2>/dev/null || warn "Could not install rtkit (no network?)"
fi

if systemctl is-active --quiet rtkit-daemon 2>/dev/null; then
    log "rtkit-daemon is running"
else
    systemctl start rtkit-daemon 2>/dev/null && log "rtkit-daemon started" || warn "Could not start rtkit-daemon"
fi

# ── Step 3: Update systemd service for PAM limits ─────────────────────
echo ""
echo "--- Step 3: Check systemd service for PAM support ---"

SERVICE_FILES=("/etc/systemd/system/soundsync.service" "/home/$AUDIO_USER/.config/systemd/user/soundsync.service")
for svc in "${SERVICE_FILES[@]}"; do
    if [ -f "$svc" ]; then
        if grep -q "LimitRTPRIO=" "$svc" 2>/dev/null; then
            log "$svc already has LimitRTPRIO"
        else
            # Add RT limits directly in the service file
            if grep -q "\[Service\]" "$svc"; then
                sed -i '/\[Service\]/a LimitRTPRIO=95\nLimitMEMLOCK=infinity\nLimitNICE=-15' "$svc"
                log "Added RT limits to $svc"
            fi
        fi
    fi
done

systemctl daemon-reload 2>/dev/null || true

# ── Step 4: CPU Governor ──────────────────────────────────────────────
echo ""
echo "--- Step 4: CPU frequency governor ---"

CURRENT_GOV=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null || echo "unknown")
echo "  Current governor: $CURRENT_GOV"

if [ "$CURRENT_GOV" = "performance" ]; then
    log "Already set to 'performance'"
elif [ "$CURRENT_GOV" = "schedutil" ] || [ "$CURRENT_GOV" = "powersave" ]; then
    # Try to set performance
    if command -v cpupower &>/dev/null; then
        cpupower frequency-set -g performance 2>/dev/null && log "Set governor to 'performance'" || warn "Could not set governor"
    else
        # Direct sysfs write
        for f in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
            echo "performance" > "$f" 2>/dev/null || true
        done
        NEW_GOV=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null || echo "unknown")
        if [ "$NEW_GOV" = "performance" ]; then
            log "Set governor to 'performance' via sysfs"
        else
            warn "Could not change governor (may need cpupower: apt install linux-tools-common)"
        fi
    fi
fi

# ── Step 5: Increase UDP buffer sizes ─────────────────────────────────
echo ""
echo "--- Step 5: Network buffer sizes for WebRTC ---"

WMEM_MAX=$(cat /proc/sys/net/core/wmem_max 2>/dev/null || echo "0")
if [ "$WMEM_MAX" -lt 2097152 ] 2>/dev/null; then
    sysctl -w net.core.wmem_max=2097152 >/dev/null 2>&1 || true
    sysctl -w net.core.rmem_max=2097152 >/dev/null 2>&1 || true
    sysctl -w net.core.wmem_default=262144 >/dev/null 2>&1 || true
    sysctl -w net.core.rmem_default=262144 >/dev/null 2>&1 || true
    log "Increased UDP buffer sizes (wmem_max=2MB)"

    # Make persistent
    SYSCTL_CONF="/etc/sysctl.d/99-soundsync-network.conf"
    cat > "$SYSCTL_CONF" << 'SYSEOF'
# Larger UDP buffers for WebRTC audio streaming
net.core.wmem_max=2097152
net.core.rmem_max=2097152
net.core.wmem_default=262144
net.core.rmem_default=262144
SYSEOF
    log "Persisted to $SYSCTL_CONF"
else
    log "UDP buffers already adequate ($WMEM_MAX bytes)"
fi

# ── Step 6: Kill zombie processes ─────────────────────────────────────
echo ""
echo "--- Step 6: Clean up zombie processes ---"

ZOMBIES=$(ps aux | grep -E '\[pipewire\].*defunct|\[parec\].*defunct|\[ffmpeg\].*defunct' | grep -v grep | awk '{print $2}' || true)
if [ -n "$ZOMBIES" ]; then
    warn "Found zombie audio processes: $ZOMBIES"
    # Zombies can't be killed directly — need to restart parent
    warn "These will be cleaned up when SoundSync restarts"
else
    log "No zombie audio processes found"
fi

# ── Step 7: Check stale pipewire-pulse ────────────────────────────────
echo ""
echo "--- Step 7: Check for stale PipeWire services ---"

PW_PID=$(pgrep -u "$AUDIO_USER" -x pipewire 2>/dev/null || true)
PW_PULSE_PID=$(pgrep -u "$AUDIO_USER" -x pipewire-pulse 2>/dev/null || true)

if [ -n "$PW_PID" ] && [ -n "$PW_PULSE_PID" ]; then
    PW_START=$(ps -o lstart= -p "$PW_PID" 2>/dev/null || echo "unknown")
    PP_START=$(ps -o lstart= -p "$PW_PULSE_PID" 2>/dev/null || echo "unknown")
    echo "  pipewire      (PID $PW_PID): started $PW_START"
    echo "  pipewire-pulse (PID $PW_PULSE_PID): started $PP_START"

    # If they started more than 1 hour apart, the pulse instance is stale
    PW_EPOCH=$(date -d "$PW_START" +%s 2>/dev/null || echo "0")
    PP_EPOCH=$(date -d "$PP_START" +%s 2>/dev/null || echo "0")
    DIFF=$(( PW_EPOCH - PP_EPOCH ))
    if [ "$DIFF" -gt 3600 ] || [ "$DIFF" -lt -3600 ]; then
        warn "pipewire-pulse started ${DIFF}s before/after pipewire — likely stale"
        warn "Consider: su - $AUDIO_USER -c 'systemctl --user restart pipewire-pulse'"
    else
        log "PipeWire services are in sync"
    fi
fi

# ── Step 8: Restart services ──────────────────────────────────────────
echo ""
echo "--- Step 8: Restart services to apply changes ---"

XDG_RUNTIME_DIR="/run/user/$AUDIO_UID"
DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
export XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS

echo "  Restarting PipeWire for user $AUDIO_USER..."
su - "$AUDIO_USER" -s /bin/bash -c "
    export XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    export DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS
    systemctl --user restart pipewire pipewire-pulse wireplumber 2>/dev/null || true
" && log "PipeWire services restarted" || warn "Could not restart PipeWire (may need manual restart)"

sleep 2

echo "  Restarting SoundSync..."
systemctl restart soundsync 2>/dev/null && log "SoundSync restarted" || warn "Could not restart soundsync service"

sleep 3

# ── Step 9: Verify ────────────────────────────────────────────────────
echo ""
echo "--- Step 9: Verification ---"

echo ""
echo "  Process scheduling after restart:"
for proc in pipewire wireplumber parec soundsync; do
    PID=$(pgrep -u "$AUDIO_USER" -x "$proc" 2>/dev/null | head -1 || true)
    if [ -n "$PID" ]; then
        SCHED=$(chrt -p "$PID" 2>/dev/null || echo "unknown")
        echo "    $proc (PID $PID): $SCHED"
    fi
done

echo ""
echo "  RTPRIO limit for $AUDIO_USER:"
su - "$AUDIO_USER" -s /bin/bash -c "ulimit -r" 2>/dev/null || echo "  Cannot check (user session needed)"

echo ""
echo "  CPU governor:"
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null || echo "  unknown"

echo ""
echo "  UDP buffer sizes:"
echo "    wmem_max: $(cat /proc/sys/net/core/wmem_max 2>/dev/null) bytes"
echo "    rmem_max: $(cat /proc/sys/net/core/rmem_max 2>/dev/null) bytes"

echo ""
echo "======================================================================"
echo " Done! If scheduling still shows SCHED_OTHER, the user may need to"
echo " log out and back in for PAM limits to take effect."
echo ""
echo " Test audio playback now and re-run audio-stutter-debug.sh to verify."
echo "======================================================================"
